name: validate-doc-structure

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  validate-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run setup
        run: ./scripts/setup.sh
      - name: Validate structure
        run: ./scripts/validate-structure.sh
